# On an incoming pull request, use Black to reformat the python code.

name: Reformat with Black
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Black
        run: pip install black
      - name: Run Black Formatter
        run: black --check .
