---
name: python
on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.10.0"

jobs:
  python:
    runs-on: ubuntu-20.04
    name: python
    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: run black formatter
        run: black --check .

      - name: run flake8 linter
        # Ignore linting errors that the black formatter is opiniated about
        run: flake8 --ignore E501,W503 .

      - name: run bandit security scan
        run: bandit -r .
